version: '3.8'

services:
  laravel-app:
    image: assetmanagement    
    ports:
      - "2309:2309"            
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb-container
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - laravel-network
    command: >
      sh -c "php artisan key:generate &&
             php artisan config:cache &&
             php artisan serve --host=0.0.0.0 --port=2309"

networks:
  laravel-network:
    driver: bridge